# Nome da pipeline - exibe o tipo de trigger que acionou a execu칞칚o
name: Pipeline de testes do Ecommerce
run-name: ${{ github.event_name }}

# Gatilho para execu칞칚o: roda automaticamente em push para a branch main
on:
  push:
    branches: [ main ]

jobs:
  run-cypress-tests:
    # Define o sistema operacional do runner
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Faz checkout do c칩digo do reposit칩rio
      - name: 游닌 Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configura o Node.js na vers칚o 20.x
      - name: 游릭 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Passo 3: Instala as depend칡ncias definidas no package-lock.json
      - name: 游닍 Install dependencies
        run: npm ci

      # Passo 4: Executa os testes automatizados com Cypress no Chrome, modo headless
      - name: 游 Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          browser: chrome
          headless: true

     
